server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: micro-service-1-id
          uri: http://localhost:8081/
          predicates:
            - Path=/**
        - id: micro-service-2-id
          uri: http://localhost:8081/
          predicates:
            - Path=/formations/**
        - id: micro-service-3-id
          uri: http://localhost:8081/
          predicates:
            - Path=/etudiants/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header