server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: banque
          uri: http://localhost:8081/
          predicates:
            - Path=/**
        - id: site-E-commerce-backend
          uri: http://localhost:8090/
          predicates:
            - Path=/**
        - id: site-E-commerce-frontend
          uri: http://localhost:4200/
          predicates:
            - Path=/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header